theme: jekyll-theme-minimal
title: Learn Unity
description: This book is obsolete
show_downloads: true
logo: /images/icons/cat/catglasses.svg
book: https://www.amazon.com/Learn-Unity-Development-Technology-Action/dp/1430248750
copyright: Technicat LLC
